# wavefront_collector_configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-config
  namespace: wavefront
data:
  collector.yaml: |
    clusterName: k8s-demo-cluster
    enableDiscovery: true

    sinks:
    - proxyAddress: example-wavefrontproxy.wavefront.svc.cluster.local:2878
      tags:
        version: 1.0.0-rc8

    sources:
      kubernetes_source:
        url: 'https://kubernetes.default.svc'
        kubeletPort: 10250
        kubeletHttps: true
        useServiceAccount: true
        insecure: true
        prefix: 'kubernetes.'

      internal_stats_source:
        prefix: 'kubernetes.'

      telegraf_sources:
      - plugins: []

    discovery:
      discovery_interval: 1m
      plugins:
      - name: redis
        type: telegraf/redis
        selectors:
          images:
          - 'redis:*'
          - '*redis*'
        port: 6379
        scheme: "tcp"
        conf: |
          servers = ["${server}"]
      - name: memcached
        type: telegraf/memcached
        selectors:
          images:
          - 'memcached:*'
        port: 11211
        conf: |
          servers = ["${host}:${port}"]
      - name: consul
        type: telegraf/consul
        selectors:
          images:
          - 'consul*'
        port: 8500
        conf: |
          address = ["${host}:${port}"]
          scheme = "http"
      - name: kube-dns-discovery
        type: prometheus
        selectors:
          labels:
            k8s-app:
            - kube-dns
        port: 10054
        path: /metrics
        scheme: http
        prefix: kube.dns.
---
# wavefront_collector_cr.yaml
apiVersion: wavefront.com/v1alpha1
kind: WavefrontCollector
metadata:
  name: wavefront-collector
  namespace: wavefront
spec:
  image: wavefronthq/wavefront-kubernetes-collector:1.0.0-rc8
  daemon: true
  configName: collector-config

  env:
  - name: HOST_PROC
    value: /host/proc
  - name: POD_NODE_NAME
    valueFrom:
      fieldRef:
        apiVersion: v1
        fieldPath: spec.nodeName
  - name: POD_NAMESPACE_NAME
    valueFrom:
      fieldRef:
        apiVersion: v1
        fieldPath: metadata.namespace

  tolerations:
  - effect: NoSchedule
    key: node.alpha.kubernetes.io/role
    operator: Exists
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists
